const xml = '<layout> \n\
  <panel>\n\
    <x>1</x>\n\
    <y>1</y>\n\
    <bar_spacing>5</bar_spacing>\n\
    <min_bar_spacing>0.5</min_bar_spacing>\n\
    <chart>\n\
      <symbol>BTCUSDT</symbol>\n\
      <color>blue</color>\n\
      <type>addLineSeries</type>\n\
      <settings>\n\
        <priceScaleId>left</priceScaleId>\n\
        <visible>true</visible>\n\
        <lineStyle>0</lineStyle>\n\
        <lineWidth>1</lineWidth>\n\
        <precision>4</precision>\n\
      </settings>\n\
    </chart>\n\
  </panel>\n\
  <panel>\n\
    <x>1</x>\n\
    <y>2</y>\n\
    <bar_spacing>5</bar_spacing>\n\
    <min_bar_spacing>0.5</min_bar_spacing>\n\
    <chart>\n\
      <symbol>BTCUSDT</symbol>\n\
      <color>red</color>\n\
      <type>addLineSeries</type>\n\
      <settings>\n\
        <priceScaleId>left</priceScaleId>\n\
        <visible>true</visible>\n\
        <lineStyle>0</lineStyle>\n\
        <lineWidth>1</lineWidth>\n\
        <precision>4</precision>\n\
      </settings>\n\
    </chart>\n\
  </panel>\n\
  <panel>\n\
    <x>1</x>\n\
    <y>3</y>\n\
    <bar_spacing>5</bar_spacing>\n\
    <min_bar_spacing>0.5</min_bar_spacing>\n\
    <chart>\n\
      <symbol>BTCUSDT</symbol>\n\
      <color>green</color>\n\
      <type>addLineSeries</type>\n\
      <settings>\n\
        <priceScaleId>left</priceScaleId>\n\
        <visible>true</visible>\n\
        <lineStyle>0</lineStyle>\n\
        <lineWidth>1</lineWidth>\n\
        <precision>4</precision>\n\
      </settings>\n\
    </chart>\n\
  </panel>\n\
  <panel>\n\
    <x>2</x>\n\
    <y>1</y>\n\
    <bar_spacing>5</bar_spacing>\n\
    <min_bar_spacing>0.5</min_bar_spacing>\n\
    <chart>\n\
      <symbol>BTCUSDT</symbol>\n\
      <color>black</color>\n\
      <type>addLineSeries</type>\n\
      <settings>\n\
        <priceScaleId>left</priceScaleId>\n\
        <visible>true</visible>\n\
        <lineStyle>0</lineStyle>\n\
        <lineWidth>1</lineWidth>\n\
        <precision>4</precision>\n\
      </settings>\n\
    </chart>\n\
  </panel>\n\
</layout>'


export { xml }